### PR TITLE
merge dev branch

### PR DESCRIPTION
**Pull request by Jackojc**
Lots of changes have been made to the language, enough to call this wot++ v2.

### CODE REVIEW

**Comment by jlagarespo** [comment]
dew it

**Review by jlagarespo — APPROVED** [review]
LGTM

**Review by qookei — APPROVED** [review]
TL;DR LGTM :^)

**Comment by jlagarespo** [comment]
nice, now merge

**Comment by Unicode-Hater** [comment]
lgtm

**Pull request merged**
